{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyM6Rj8bTeLUbW7vg83uTTgV",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/leehuichann/LinearAlgebra1/blob/main/6%EC%A3%BC%EC%B0%A8%EA%B3%BC%EC%A0%9C_202315167.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 1**"
      ],
      "metadata": {
        "id": "p_Ehcyn888Jh"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "\n",
        "np.set_printoptions(suppress=True, precision=2)\n",
        "\n",
        "# 행렬 A\n",
        "A = np.array([\n",
        "    [1, 2, 3],\n",
        "    [2, 5, 3],\n",
        "    [1, 0, 8]\n",
        "], dtype=float)\n",
        "\n",
        "# 단위행렬 I\n",
        "I = np.eye(3)\n",
        "\n",
        "# 첨가행렬 [ A l I]\n",
        "AI = np.hstack((A, I))\n",
        "\n",
        "def show_matrix(operation) :\n",
        "  \"\"\"행 연산 과정 출력\"\"\"\n",
        "  print(f\"\\n{operation}\")\n",
        "  print(AI)\n",
        "\n",
        "print(\"초기 첨가행렬 [A | I]\")\n",
        "print(AI)\n",
        "\n",
        "# 1단계 : 첫 번째 열에서 1행 아래의 원소를 0으로 만든다.\n",
        "AI[1] = (-2) * AI[0] + AI[1]\n",
        "show_matrix(\"R2 ← (-2)R1 + R2\")\n",
        "\n",
        "AI[2] = (-1) * AI[0] + AI[2]\n",
        "show_matrix(\"R3 ← (-1)R1 + R3\")\n",
        "\n",
        "# 2단계 : 두 번째 열에서 피벗 아래의 원소를 0으로 만든다.\n",
        "AI[2] = 2 * AI[1] + AI[2]\n",
        "show_matrix(\"R3 ← 2R2 + R3\")\n",
        "\n",
        "# 3단계 : 세 번째 피벗을 1로 만든다.\n",
        "AI[2] = (-1) * AI[2]\n",
        "show_matrix(\"R3 ← (-1)R3\")\n",
        "\n",
        "# 4단계 : 세 번째 열에서 피벗 위의 원소를 0으로 만든다.\n",
        "AI[1] = AI[1] + 3 * AI[2]\n",
        "show_matrix(\"R2 ← R2 + 3R3\")\n",
        "\n",
        "AI[0] = AI[0] - 3 * AI[2]\n",
        "show_matrix(\"R1 ← R1 - 3R3\")\n",
        "\n",
        "# 5단계 : 두 번째 열에서 피벗 위의 원소를 0으로 만든다.\n",
        "AI[0] = AI[0] - 2 * AI[1]\n",
        "show_matrix(\"R1 ← R1 - 2R2\")\n",
        "\n",
        "# 오른쪽 부분이 A의 역행렬\n",
        "A_inverse = AI[:, 3:]\n",
        "\n",
        "print(\"\\n최종 첨가행렬 [I | A^(-1)]\")\n",
        "print(AI)\n",
        "\n",
        "print(\"\\nA의 역행렬\")\n",
        "print(A_inverse)\n",
        "\n",
        "# 역행렬 검산\n",
        "print(\"\\n검산 : A x A^(-1)\")\n",
        "print(A @ A_inverse)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1LjnZwsM872A",
        "outputId": "3a4cc8c2-d4e8-4a74-ae37-8241b68b51b8"
      },
      "execution_count": 59,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "초기 첨가행렬 [A | I]\n",
            "[[1. 2. 3. 1. 0. 0.]\n",
            " [2. 5. 3. 0. 1. 0.]\n",
            " [1. 0. 8. 0. 0. 1.]]\n",
            "\n",
            "R2 ← (-2)R1 + R2\n",
            "[[ 1.  2.  3.  1.  0.  0.]\n",
            " [ 0.  1. -3. -2.  1.  0.]\n",
            " [ 1.  0.  8.  0.  0.  1.]]\n",
            "\n",
            "R3 ← (-1)R1 + R3\n",
            "[[ 1.  2.  3.  1.  0.  0.]\n",
            " [ 0.  1. -3. -2.  1.  0.]\n",
            " [ 0. -2.  5. -1.  0.  1.]]\n",
            "\n",
            "R3 ← 2R2 + R3\n",
            "[[ 1.  2.  3.  1.  0.  0.]\n",
            " [ 0.  1. -3. -2.  1.  0.]\n",
            " [ 0.  0. -1. -5.  2.  1.]]\n",
            "\n",
            "R3 ← (-1)R3\n",
            "[[ 1.  2.  3.  1.  0.  0.]\n",
            " [ 0.  1. -3. -2.  1.  0.]\n",
            " [-0. -0.  1.  5. -2. -1.]]\n",
            "\n",
            "R2 ← R2 + 3R3\n",
            "[[ 1.  2.  3.  1.  0.  0.]\n",
            " [ 0.  1.  0. 13. -5. -3.]\n",
            " [-0. -0.  1.  5. -2. -1.]]\n",
            "\n",
            "R1 ← R1 - 3R3\n",
            "[[  1.   2.   0. -14.   6.   3.]\n",
            " [  0.   1.   0.  13.  -5.  -3.]\n",
            " [ -0.  -0.   1.   5.  -2.  -1.]]\n",
            "\n",
            "R1 ← R1 - 2R2\n",
            "[[  1.   0.   0. -40.  16.   9.]\n",
            " [  0.   1.   0.  13.  -5.  -3.]\n",
            " [ -0.  -0.   1.   5.  -2.  -1.]]\n",
            "\n",
            "최종 첨가행렬 [I | A^(-1)]\n",
            "[[  1.   0.   0. -40.  16.   9.]\n",
            " [  0.   1.   0.  13.  -5.  -3.]\n",
            " [ -0.  -0.   1.   5.  -2.  -1.]]\n",
            "\n",
            "A의 역행렬\n",
            "[[-40.  16.   9.]\n",
            " [ 13.  -5.  -3.]\n",
            " [  5.  -2.  -1.]]\n",
            "\n",
            "검산 : A x A^(-1)\n",
            "[[1. 0. 0.]\n",
            " [0. 1. 0.]\n",
            " [0. 0. 1.]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "실습 2"
      ],
      "metadata": {
        "id": "OwZUIqBV8sOr"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "np.set_printoptions(suppress=True, precision=2)\n",
        "\n",
        "# 행렬 A\n",
        "A = np.array([\n",
        "    [1, -3, 4],\n",
        "    [2, -5, 7],\n",
        "    [0, -1, 1]\n",
        "], dtype=float)\n",
        "\n",
        "# 단위행렬 I\n",
        "I = np.eye(3)\n",
        "\n",
        "# 첨가행렬 [A | I]\n",
        "AI = np.hstack((A, I))\n",
        "\n",
        "def show_matrix(title) :\n",
        "  \"\"\"첨가행렬을 [A | I] 형태로 출력\"\"\"\n",
        "  print(f\"\\n{title}\")\n",
        "\n",
        "  for row in AI :\n",
        "    left = \" \".join(f\"{value:6.1f}\" for value in row[:3])\n",
        "    right = \" \".join(f\"{value:6.1f}\" for value in row[3:])\n",
        "    print(f\"[{left} | {right}]\")\n",
        "\n",
        "# 초기 첨가행렬\n",
        "show_matrix(\"초기 첨가행렬 [A | I]\")\n",
        "\n",
        "# 1단계 : R2 ← (-2)R1 + R2\n",
        "AI[1] = (-2) * AI[0] + AI[1]\n",
        "show_matrix(\"1단계 : R2 ← (-2)R1 + R2\")\n",
        "\n",
        "# 2단계 : R3 ← R2 * R3\n",
        "AI[2] = AI[1] + AI[2]\n",
        "show_matrix(\"2단계 : R3 ← R2 + R3\")\n",
        "\n",
        "# 3단계 : R1 ← 3R2 + R1\n",
        "AI[0] = 3 * AI[1] + AI[0]\n",
        "show_matrix(\"3단계 : R1 ← 3R2 + R1\")\n",
        "\n",
        "# 왼쪽 A 부분과 오른쪽 부분 분리\n",
        "left_matrix = AI[:, :3]\n",
        "right_matrix = AI[:, 3:]\n",
        "\n",
        "print(\"\\n행 연산 후 왼쪽 행렬\")\n",
        "print(left_matrix)\n",
        "print(\"\\n행 연산 후 오른쪽 행렬\")\n",
        "print(right_matrix)\n",
        "\n",
        "# 역행렬 존재 여부 확인\n",
        "if np.linalg.matrix_rank(A) < A.shape[0] :\n",
        "  print(\"\\n판정 결과\")\n",
        "  print(\"A의 행들이 선형종속입니다.\")\n",
        "  print(\"왼쪽 행렬에 모든 원소가 0인 행이 발생했습니다.\")\n",
        "  print(\"따라서 A를 단위행렬로 만들 수 없습니다.\")\n",
        "  print(\"행렬 A의 역행렬은 존재하지 않습니다.\")\n",
        "else :\n",
        "  A_inverse = right_matrix\n",
        "  print(\"\\nA의 역행렬\")\n",
        "  print(A_inverse)\n",
        "\n",
        "det_A = np.linalg.det(A)\n",
        "print(\"det(A) =\", round(det_A))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Zg_b3J2C8r15",
        "outputId": "8c8dd09f-0639-4480-a315-8d73255f9adb"
      },
      "execution_count": 60,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "초기 첨가행렬 [A | I]\n",
            "[   1.0   -3.0    4.0 |    1.0    0.0    0.0]\n",
            "[   2.0   -5.0    7.0 |    0.0    1.0    0.0]\n",
            "[   0.0   -1.0    1.0 |    0.0    0.0    1.0]\n",
            "\n",
            "1단계 : R2 ← (-2)R1 + R2\n",
            "[   1.0   -3.0    4.0 |    1.0    0.0    0.0]\n",
            "[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]\n",
            "[   0.0   -1.0    1.0 |    0.0    0.0    1.0]\n",
            "\n",
            "2단계 : R3 ← R2 + R3\n",
            "[   1.0   -3.0    4.0 |    1.0    0.0    0.0]\n",
            "[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]\n",
            "[   0.0    0.0    0.0 |   -2.0    1.0    1.0]\n",
            "\n",
            "3단계 : R1 ← 3R2 + R1\n",
            "[   1.0    0.0    1.0 |   -5.0    3.0    0.0]\n",
            "[   0.0    1.0   -1.0 |   -2.0    1.0    0.0]\n",
            "[   0.0    0.0    0.0 |   -2.0    1.0    1.0]\n",
            "\n",
            "행 연산 후 왼쪽 행렬\n",
            "[[ 1.  0.  1.]\n",
            " [ 0.  1. -1.]\n",
            " [ 0.  0.  0.]]\n",
            "\n",
            "행 연산 후 오른쪽 행렬\n",
            "[[-5.  3.  0.]\n",
            " [-2.  1.  0.]\n",
            " [-2.  1.  1.]]\n",
            "\n",
            "판정 결과\n",
            "A의 행들이 선형종속입니다.\n",
            "왼쪽 행렬에 모든 원소가 0인 행이 발생했습니다.\n",
            "따라서 A를 단위행렬로 만들 수 없습니다.\n",
            "행렬 A의 역행렬은 존재하지 않습니다.\n",
            "det(A) = 0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 3**"
      ],
      "metadata": {
        "id": "xL6wou77UqyF"
      }
    },
    {
      "cell_type": "code",
      "execution_count": 61,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2CFlMEt-OXkb",
        "outputId": "7a1c5554-2c93-4e2c-8e6d-08b454b8d795"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "행렬 A\n",
            "[[1. 2. 3.]\n",
            " [2. 5. 3.]\n",
            " [1. 0. 8.]]\n",
            "\n",
            "행렬식 det(A)\n",
            "-1\n",
            "\n",
            "여인수행렬 C\n",
            "[[ 40. -13.  -5.]\n",
            " [-16.   5.   2.]\n",
            " [ -9.   3.   1.]]\n",
            "\n",
            "수반행렬 adj(A)\n",
            "[[ 40. -16.  -9.]\n",
            " [-13.   5.   3.]\n",
            " [ -5.   2.   1.]]\n",
            "\n",
            "역행렬 A^(-1)\n",
            "[[-40.  16.   9.]\n",
            " [ 13.  -5.  -3.]\n",
            " [  5.  -2.  -1.]]\n",
            "\n",
            "검산 A x A^(-1)\n",
            "[[1. 0. 0.]\n",
            " [0. 1. 0.]\n",
            " [0. 0. 1.]]\n"
          ]
        }
      ],
      "source": [
        "import numpy as np\n",
        "\n",
        "# 원래 행렬\n",
        "A = np.array([\n",
        "    [1, 2, 3],\n",
        "    [2, 5, 3],\n",
        "    [1, 0, 8]\n",
        "], dtype = float)\n",
        "\n",
        "# (i, j)번째 행과 열을 제거한 소행렬\n",
        "def get_minor(matrix, row, col) :\n",
        "  return np.delete(\n",
        "      np.delete(matrix, row, axis = 0),\n",
        "      col,\n",
        "      axis = 1\n",
        "  )\n",
        "\n",
        "# 여인수행렬 계산\n",
        "def cofactor_matrix(matrix) :\n",
        "  n = matrix.shape[0]\n",
        "  C = np.zeros((n,n))\n",
        "  for i in range(n) :\n",
        "    for j in range(n) :\n",
        "      minor = get_minor(matrix, i, j)\n",
        "      C[i, j] = ((-1) ** (i + j)) * np.linalg.det(minor)\n",
        "\n",
        "  return C\n",
        "\n",
        "# 행렬식 계산\n",
        "det_A = round(np.linalg.det(A))\n",
        "\n",
        "if det_A == 0 :\n",
        "  print(\"행렬식이 0이므로 역행렬이 존재하지 않습니다.\")\n",
        "else :\n",
        "  # 1. 여인수행렬\n",
        "  C = cofactor_matrix(A)\n",
        "  # 2. 수반행렬 = 여인수행렬의 전치행렬\n",
        "  adj_A = C.T\n",
        "  # 3. 역행렬\n",
        "  inverse_A = (1 / det_A) * adj_A\n",
        "  # 부동소수점 오차 정리\n",
        "  C = np.round(C, 10)\n",
        "  adj_A = np.round(adj_A, 10)\n",
        "  inverse_A = np.round(inverse_A, 10)\n",
        "\n",
        "  print(\"행렬 A\")\n",
        "  print(A)\n",
        "  print(\"\\n행렬식 det(A)\")\n",
        "  print(det_A)\n",
        "  print(\"\\n여인수행렬 C\")\n",
        "  print(C)\n",
        "  print(\"\\n수반행렬 adj(A)\")\n",
        "  print(adj_A)\n",
        "  print(\"\\n역행렬 A^(-1)\")\n",
        "  print(inverse_A)\n",
        "  print(\"\\n검산 A x A^(-1)\")\n",
        "  print(np.round(A @ inverse_A, 10))\n"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 4**"
      ],
      "metadata": {
        "id": "prqhYnbMX-Qn"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "np.set_printoptions(suppress=True, precision=2)\n",
        "\n",
        "# 계수행렬 A\n",
        "A = np.array([\n",
        "    [1, 2, 3],\n",
        "    [1, 3, 6],\n",
        "    [2, 6, 13]\n",
        "], dtype=float)\n",
        "\n",
        "# 상수벡터 b\n",
        "b = np.array([\n",
        "    [1],\n",
        "    [3],\n",
        "    [5]\n",
        "], dtype=float)\n",
        "\n",
        "print(\"계수행렬 A\")\n",
        "print(A)\n",
        "print(\"\\n상수벡터 b\")\n",
        "print(b)\n",
        "\n",
        "# 행렬식 계산\n",
        "det_A = np.linalg.det(A)\n",
        "print(\"\\n행렬식 det(A)\")\n",
        "print(round(det_A, 10))\n",
        "\n",
        "# 역행렬 존재 여부 확인\n",
        "if np.isclose(det_A, 0) :\n",
        "  print(\"\\ndet(A) = 0 이므로 역행렬이 존재하지 않습니다.\")\n",
        "else :\n",
        "  # A의 역행렬\n",
        "  A_inverse = np.linalg.inv(A)\n",
        "\n",
        "  print(\"\\nA의 역행렬\")\n",
        "  print(A_inverse)\n",
        "  # X = A^(-1)b\n",
        "  X = A_inverse @ b\n",
        "  print(\"\\n선형시스템의 해\")\n",
        "  print(X)\n",
        "\n",
        "  x, y, z = X.flatten()\n",
        "  print(f\"\\nx = {x:0f}\")\n",
        "  print(f\"y = {y:0f}\")\n",
        "  print(f\"z = {z:0f}\")\n",
        "\n",
        "  # 검산\n",
        "  print(\"\\n검산 결과 A @ X\")\n",
        "  print(A @ X)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "c47Chvk1YAts",
        "outputId": "cdd9bcb6-a218-4064-b1b2-e84a3cf55ecb"
      },
      "execution_count": 62,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "계수행렬 A\n",
            "[[ 1.  2.  3.]\n",
            " [ 1.  3.  6.]\n",
            " [ 2.  6. 13.]]\n",
            "\n",
            "상수벡터 b\n",
            "[[1.]\n",
            " [3.]\n",
            " [5.]]\n",
            "\n",
            "행렬식 det(A)\n",
            "1.0\n",
            "\n",
            "A의 역행렬\n",
            "[[ 3. -8.  3.]\n",
            " [-1.  7. -3.]\n",
            " [-0. -2.  1.]]\n",
            "\n",
            "선형시스템의 해\n",
            "[[-6.]\n",
            " [ 5.]\n",
            " [-1.]]\n",
            "\n",
            "x = -6.000000\n",
            "y = 5.000000\n",
            "z = -1.000000\n",
            "\n",
            "검산 결과 A @ X\n",
            "[[1.]\n",
            " [3.]\n",
            " [5.]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 5**"
      ],
      "metadata": {
        "id": "HUzwKfS5cR_d"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# 2 x 2 행렬의 행렬식 계산 함수\n",
        "def determinant_2x2(matrix) :\n",
        "  return (\n",
        "      matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0])\n",
        "\n",
        "# 계수 행렬 A\n",
        "A = [\n",
        "    [3, -2],\n",
        "    [-5, 4]\n",
        "]\n",
        "# 상수벡터 b\n",
        "b = [6, 8]\n",
        "\n",
        "# A1 : A의 첫 번째 열을 b로 교체\n",
        "A1 = [\n",
        "    [b[0], A[0][1]],\n",
        "    [b[1], A[1][1]]\n",
        "]\n",
        "\n",
        "# A2 : A의 두 번째 열을 b로 교체\n",
        "A2 = [\n",
        "    [A[0][0], b[0]],\n",
        "    [A[1][0], b[1]]\n",
        "]\n",
        "\n",
        "# 각각의 행렬식 계산\n",
        "D = determinant_2x2(A)\n",
        "D1 = determinant_2x2(A1)\n",
        "D2 = determinant_2x2(A2)\n",
        "\n",
        "print(\"계수행렬 A =\", A)\n",
        "print(\"A1 = \", A1)\n",
        "print(\"A2 = \", A2)\n",
        "print(\"\\ndet(A) =\", D)\n",
        "print(\"det(A1) =\", D1)\n",
        "print(\"det(A2) =\", D2)\n",
        "\n",
        "# 크래머의 규칙 적용\n",
        "if D == 0 :\n",
        "  print(\"\\ndet(A)가 0 이므로 크래머의 규칙을 적용할 수 없습니다.\")\n",
        "else :\n",
        "  x1 = D1 / D\n",
        "  x2 = D2 / D\n",
        "  print(\"\\n크래머의 규칙 계산\")\n",
        "  print(f\"x1 = det(A1) / det(A) = {D1} / {D} = {x1}\")\n",
        "  print(f\"x2 = det(A2) / det(A) = {D2} / {D} = {x2}\")\n",
        "  print(\"\\n선형시스템의 해\")\n",
        "  print(f\"x1 = {x1}\")\n",
        "  print(f\"x2 = {x2}\")\n",
        "\n",
        "# rjatks\n",
        "result1 = 3 * x1 - 2 * x2\n",
        "result2 = -5 * x1 + 4 * x2\n",
        "print(\"\\n검산\")\n",
        "print(f\"3x1 - 2x2 = {result1 }\")\n",
        "print(f\"-5x1 + 4x2 = {result2}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "GYUS-KFMcUWJ",
        "outputId": "ff4566e6-16f1-4b7b-fcbf-c6c878353b13"
      },
      "execution_count": 63,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "계수행렬 A = [[3, -2], [-5, 4]]\n",
            "A1 =  [[6, -2], [8, 4]]\n",
            "A2 =  [[3, 6], [-5, 8]]\n",
            "\n",
            "det(A) = 2\n",
            "det(A1) = 40\n",
            "det(A2) = 54\n",
            "\n",
            "크래머의 규칙 계산\n",
            "x1 = det(A1) / det(A) = 40 / 2 = 20.0\n",
            "x2 = det(A2) / det(A) = 54 / 2 = 27.0\n",
            "\n",
            "선형시스템의 해\n",
            "x1 = 20.0\n",
            "x2 = 27.0\n",
            "\n",
            "검산\n",
            "3x1 - 2x2 = 6.0\n",
            "-5x1 + 4x2 = 8.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 6**"
      ],
      "metadata": {
        "id": "YrMEnh1J9EoJ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "np.set_printoptions(suppress=True, precision=2)\n",
        "\n",
        "# 계수 행렬 A\n",
        "A = np.array([\n",
        "    [1, -1, 1],\n",
        "    [1, 1, -2],\n",
        "    [1, 2, 1]\n",
        "], dtype=float)\n",
        "\n",
        "# 상수벡터 b\n",
        "b = np.array([0, 1, 6], dtype=float)\n",
        "# 기준 행렬식 D = det(A)\n",
        "D = round(np.linalg.det(A))\n",
        "\n",
        "print(\"계수행렬 A\")\n",
        "print(A)\n",
        "print(\"\\n상수벡터 b\")\n",
        "print(b)\n",
        "print(f\"\\nD = det(A) = {D}\")\n",
        "\n",
        "if D == 0 :\n",
        "  print(\"det(A)가 0이므로 크래머의 규칙을 적용할 수 없습니다.\")\n",
        "else :\n",
        "  determinants = []\n",
        "  solution = []\n",
        "  # A의 각 열을 b로 교체\n",
        "  for i in range(A.shape[1]) :\n",
        "    Ai = A.copy()\n",
        "    Ai[:, i] = b\n",
        "\n",
        "    Di = round(np.linalg.det(Ai))\n",
        "    xi = Di / D\n",
        "    determinants.append(Di)\n",
        "    solution.append(xi)\n",
        "\n",
        "    print(f\"\\nA{i + 1} : {i +1}번째 열을 b로 교체\")\n",
        "    print(Ai)\n",
        "    print(f\"D{i + 1} = det(A{i + 1}) = {Di}\")\n",
        "    print(\n",
        "        f\"x{i + 1} = D{i + 1}/D\"\n",
        "        f\"= {Di}/{D} = {xi}\"\n",
        "    )\n",
        "  solution = np.array(solution)\n",
        "\n",
        "  print(\"\\n최종 해\")\n",
        "  for i, value in enumerate(solution, start=1) :\n",
        "    print(f\"x{i} = {value}\")\n",
        "  # 검산\n",
        "  print(\"\\n검산 결과 A @ x\")\n",
        "  print(A @ solution)\n",
        "  print(\"\\n원래 상수벡터 b\")\n",
        "  print(b)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "qtQoCTL89G_t",
        "outputId": "7a5e9ebc-8391-40b1-de64-37639253adbd"
      },
      "execution_count": 64,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "계수행렬 A\n",
            "[[ 1. -1.  1.]\n",
            " [ 1.  1. -2.]\n",
            " [ 1.  2.  1.]]\n",
            "\n",
            "상수벡터 b\n",
            "[0. 1. 6.]\n",
            "\n",
            "D = det(A) = 9\n",
            "\n",
            "A1 : 1번째 열을 b로 교체\n",
            "[[ 0. -1.  1.]\n",
            " [ 1.  1. -2.]\n",
            " [ 6.  2.  1.]]\n",
            "D1 = det(A1) = 9\n",
            "x1 = D1/D= 9/9 = 1.0\n",
            "\n",
            "A2 : 2번째 열을 b로 교체\n",
            "[[ 1.  0.  1.]\n",
            " [ 1.  1. -2.]\n",
            " [ 1.  6.  1.]]\n",
            "D2 = det(A2) = 18\n",
            "x2 = D2/D= 18/9 = 2.0\n",
            "\n",
            "A3 : 3번째 열을 b로 교체\n",
            "[[ 1. -1.  0.]\n",
            " [ 1.  1.  1.]\n",
            " [ 1.  2.  6.]]\n",
            "D3 = det(A3) = 9\n",
            "x3 = D3/D= 9/9 = 1.0\n",
            "\n",
            "최종 해\n",
            "x1 = 1.0\n",
            "x2 = 2.0\n",
            "x3 = 1.0\n",
            "\n",
            "검산 결과 A @ x\n",
            "[0. 1. 6.]\n",
            "\n",
            "원래 상수벡터 b\n",
            "[0. 1. 6.]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 7**"
      ],
      "metadata": {
        "id": "6NbK_22d9Hc8"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import math\n",
        "# 2 x 2 행렬식 계산 함수\n",
        "def determinant_2x2(matrix) :\n",
        "  return (\n",
        "      matrix[0][0] * matrix[1][1] - matrix [0][1] * matrix[1][0]\n",
        "  )\n",
        "# 각도를 라디안으로 변환\n",
        "angle_25 = math.radians(25)\n",
        "angle_15 = math.radians(15)\n",
        "\n",
        "# 계수행렬 A\n",
        "A = [\n",
        "    [math.cos(angle_25), -math.cos(angle_15)], [math.sin(angle_25), math.sin(angle_15)]\n",
        "]\n",
        "\n",
        "# 상수벡터 b\n",
        "b = [0, 30]\n",
        "# A1 : 첫 번째 열을 b로 교체\n",
        "A1 = [\n",
        "    [b[0], A[0][1]], [b[1], A[1][1]]\n",
        "]\n",
        "# A2 : 두 번째 열을 b로 교체\n",
        "A2 = [\n",
        "    [A[0][0], b[0]], [A[1][0], b[1]]\n",
        "]\n",
        "# 행렬식 계산\n",
        "D = determinant_2x2(A)\n",
        "D1 = determinant_2x2(A1)\n",
        "D2 = determinant_2x2(A2)\n",
        "\n",
        "print(\"계수행렬 A\")\n",
        "for row in A :\n",
        "  print(row)\n",
        "print(\"\\nA1 : 첫 번째 열을 b로 교체\")\n",
        "for row in A1 :\n",
        "  print(row)\n",
        "print(\"\\nA2 : 두 번째 열을 b로 교체\")\n",
        "for row in A2 :\n",
        "  print(row)\n",
        "print(f\"\\nD = det(A) = {D: .6f}\")\n",
        "print(f\"D1 = det(A1) = {D1: .6f}\")\n",
        "print(f\"D2 = det(A2) = {D2: .6f}\")\n",
        "\n",
        "# 크래머의 규치\n",
        "if math.isclose(D, 0.0, abs_tol=1e-12) :\n",
        "  print(\"\\ndet(A)가 0이므로 유일한 해가 없습니다.\")\n",
        "else :\n",
        "  T1 = D1 / D\n",
        "  T2 = D2 / D\n",
        "  print(\"\\n크래머의 규칙 계산\")\n",
        "  print(f\"T1 = D1 / D = {D1: .6f} / {D: .6f}\")\n",
        "  print(f\"T1 = {T1: .4f}\")\n",
        "  print(f\"\\nT2 = D2 / D = {D2: .6f} / {D: .6f}\")\n",
        "  print(f\"T2 = {T2: .4f}\")\n",
        "  # 검산\n",
        "  equation1 = (\n",
        "      math.cos(angle_25) * T1 - math.cos(angle_15) * T2\n",
        "  )\n",
        "  equation2 = (\n",
        "      math.sin(angle_25) * T1 + math.sin(angle_15) * T2\n",
        "  )\n",
        "  print(\"\\n검산\")\n",
        "  print(f\"수평 방향 합 = {equation1: .6f}\")\n",
        "  print(f\"수직 바향 합 = {equation2: .6f}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "hSXya84p9Je2",
        "outputId": "e504e929-3ae9-48f2-dce2-4e975b0757f3"
      },
      "execution_count": 65,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "계수행렬 A\n",
            "[0.9063077870366499, -0.9659258262890683]\n",
            "[0.42261826174069944, 0.25881904510252074]\n",
            "\n",
            "A1 : 첫 번째 열을 b로 교체\n",
            "[0, -0.9659258262890683]\n",
            "[30, 0.25881904510252074]\n",
            "\n",
            "A2 : 두 번째 열을 b로 교체\n",
            "[0.9063077870366499, 0]\n",
            "[0.42261826174069944, 30]\n",
            "\n",
            "D = det(A) =  0.642788\n",
            "D1 = det(A1) =  28.977775\n",
            "D2 = det(A2) =  27.189234\n",
            "\n",
            "크래머의 규칙 계산\n",
            "T1 = D1 / D =  28.977775 /  0.642788\n",
            "T1 =  45.0814\n",
            "\n",
            "T2 = D2 / D =  27.189234 /  0.642788\n",
            "T2 =  42.2989\n",
            "\n",
            "검산\n",
            "수평 방향 합 =  0.000000\n",
            "수직 바향 합 =  30.000000\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "**실습 8**"
      ],
      "metadata": {
        "id": "7yJfXaoV9J54"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "# 3차원 벡터\n",
        "u1 = np.array([1, 1, 0], dtype=float)\n",
        "u2 = np.array([1, 1, 1], dtype=float)\n",
        "u3 = np.array([0, 2, 3], dtype=float)\n",
        "\n",
        "# 각 벡터를 행으로 가지는 행렬\n",
        "A = np.array([\n",
        "    u1,\n",
        "    u2,\n",
        "    u3\n",
        "])\n",
        "\n",
        "print(\"벡터 행렬 A\")\n",
        "print(A)\n",
        "\n",
        "# 행렬식 계산\n",
        "det_A = np.linalg.det(A)\n",
        "# 부동소수점 오차 정리\n",
        "det_A = round(det_A, 10)\n",
        "# 평행육면체의 체적\n",
        "volume = abs(det_A)\n",
        "\n",
        "print(\"\\n행렬식 det(A)\")\n",
        "print(det_A)\n",
        "print(\"\\n평행육면체 S의 체적\")\n",
        "print(volume)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "al3Eia8T9LzA",
        "outputId": "a50b5d8b-9092-4cd8-d8ca-f50488449e41"
      },
      "execution_count": 66,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "벡터 행렬 A\n",
            "[[1. 1. 0.]\n",
            " [1. 1. 1.]\n",
            " [0. 2. 3.]]\n",
            "\n",
            "행렬식 det(A)\n",
            "-2.0\n",
            "\n",
            "평행육면체 S의 체적\n",
            "2.0\n"
          ]
        }
      ]
    }
  ]
}